import React from 'react';
import { Navbar } from '@/components/Navbar';
import { Footer } from '@/components/Footer';

export default function TermsAndConditions() {
  const [htmlContent, setHtmlContent] = React.useState('');

  return (
    <div className="min-h-screen bg-background font-sans selection:bg-primary/20 selection:text-primary">
      <Navbar />
      <main id="main-content" className="pt-32 pb-20">
        <div className="container mx-auto px-6">
          <div className="max-w-3xl mx-auto">
            <h1 className="text-4xl md:text-5xl font-bold text-foreground mb-8">Terms &amp; Conditions</h1>
            
            <div className="prose prose-invert max-w-none">
              {htmlContent ? (
                <div 
                  dangerouslySetInnerHTML={{ __html: htmlContent }}
                  className="text-white/80 leading-relaxed space-y-4"
                />
              ) : (
                <div className="bg-white/5 border border-white/10 rounded-lg p-8 text-center">
                  <p className="text-white/60 mb-6">
                    This section contains our Terms &amp; Conditions. Paste the HTML code generated by Termly below to display your terms and conditions.
                  </p>
                  <textarea
                    placeholder="Paste your Termly HTML code here..."
                    value={htmlContent}
                    onChange={(e) => setHtmlContent(e.target.value)}
                    className="w-full h-64 p-4 bg-white/5 border border-white/10 rounded text-white/80 text-sm font-mono placeholder:text-white/30 focus:outline-none focus:border-primary/50"
                  />
                  <p className="text-white/40 text-xs mt-4">
                    The HTML will be rendered on this page once you paste it.
                  </p>
                </div>
              )}
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
